name: Bundle Tests

on:
  pull_request:
    branches:
      - 2.x
    paths:
      - .github/workflows/bundle.yml
      - composer.*
      - src/Bundle/**
      - tests/Tests/Bundle/**

  push:
    branches:
      - 2.x
    paths:
      - .github/workflows/bundle.yml
      - composer.*
      - src/Bundle/**
      - tests/Tests/Bundle/**

jobs:
  bundle:
    name: PHP ${{ matrix.php }} / Symfony ${{ matrix.symfony }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.4', '8.5']
        symfony: ['6.4', '7.4']

    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit:11

      - run: composer validate

      - run: composer require --no-update "symfony/framework-bundle:^${{ matrix.symfony }}"

      - run: composer update --no-interaction --prefer-dist --prefer-stable

      - run: phpunit --colors=always tests/Tests/Bundle/
