name: Static Analysis

on:
  pull_request:
    branches:
      - 2.x
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - src/**
      - tests/StaticAnalysis/*
      - phpstan*

  push:
    branches:
      - 2.x
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - src/**
      - tests/StaticAnalysis/*
      - phpstan*

jobs:
  static-analysis-phpstan:
    name: Static Analysis with PHPStan
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: 8.3
          tools: phpstan, cs2pr

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Run static analysis with phpstan/phpstan
        run: phpstan analyse --no-progress --error-format=checkstyle | cs2pr

