name: Tests

on:
  pull_request:
    branches:
      - 2.x
    paths:
      - .github/workflows/tests.yml
      - composer.*
      - src/**
      - tests/**

  push:
    branches:
      - 2.x
    paths:
      - .github/workflows/tests.yml
      - composer.*
      - src/**
      - tests/**

jobs:
  build:
    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.2
          - 8.3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit:11

      - run: composer validate

      - uses: "ramsey/composer-install@v2"

      - run: phpunit --colors=always --coverage-clover=coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
